---
name: CommandOverride
version: 1.0.1
main: de.timmyrs.CommandOverride
author: timmyRS
website: https://timmyrs.de

commands:
  reloadcommands:
    permission: commandoverride.reload

permissions:
  commandoverride.reload:
    default: 'op'
